<!--<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">-->
<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputPath>$(SolutionDir)/net-build/WebTest</OutputPath>
    <RunAOTCompilation>true</RunAOTCompilation>
    <WasmNativeDebugSymbols>true</WasmNativeDebugSymbols>
    <WasmNativeStrip>false</WasmNativeStrip>
    <EmccExtraLDFlags>$(EmccExtraLDFlags) -s USE_WEBGL2=1</EmccExtraLDFlags>
  </PropertyGroup>
  <ItemGroup>
    <NativeFileReference Include="$(SolutionDir)\glue-build\web\bin\DiligentCore.a"/>
<!--    <NativeFileReference Include="$(SolutionDir)\glue-build\web\bin\*.wasm"/>-->
    <ProjectReference Include="..\DiligentCore\DiligentCore.csproj" />
  </ItemGroup>
</Project>
