<!--<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">-->
<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <OutputPath>$(SolutionDir)/net-build/WebTest</OutputPath>
        <RunAOTCompilation>true</RunAOTCompilation>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <WasmAppDir>./wwwroot</WasmAppDir>
    </PropertyGroup>
    <ItemGroup>
        <WasmExtraFilesToDeploy Include="$(SolutionDir)\glue-build\web\bin\libDiligentCore.*"/>
        <ProjectReference Include="..\DiligentCore\DiligentCore.csproj"/>
    </ItemGroup>

<!-- Idk why, but it seems WasmExtraFileToDeploy stops to work-->
    <Target Name="CopyDiligentLib" BeforeTargets="Build">
        <Copy SourceFiles="@(WasmExtraFilesToDeploy)" DestinationFolder="$(SolutionDir)\DiligentCore.WebTest\wwwroot\" />
    </Target>
</Project>
