on:
  workflow_call:
    inputs:
      is_release:
        type: boolean
        default: false
jobs:
  build_net:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'
      - name: Downloading Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: '*.zip'
          merge-multiple: true
      - name: Extract Code Artifacts
        run: 7z x code-artifact.zip
      # Put it back built libraries
      - name: Extract Window Libraries
        run: 7z x windows-lib-artifact.zip "-o./glue-build/win32"
      - name: Extract Linux Libraries
        run: 7z x linux-lib-artifact.zip "-o./glue-build/linux"
      
      - name: Install dependencies
        run: npm i

      - if: inputs.is_release
        name: Update Library Version
        run: npm run ci:tag -- RELEASE_TAG=${{ github.ref_name }}

      - name: Build DiligentCore.NET
        run: npm run build:bindings
      
      - name: Run DiligentCore Tests
        run: npm run test
        env:
          CI: '1'
      
      - if: inputs.is_release
        name: Generate Nuget Package
        run: npm run pack:create

      - if: inputs.is_release
        name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: diligent-core.nupkg
          path: './net-build/Lib/*.nupkg'

      