name: Deploy

on:
  push:
    branches:
      - main
      - ci/*
jobs:
  generate-bindings:
    uses: ./.github/workflows/_generate.yml
    with:
      runs_on: 'windows-latest'
  build-windows:
    uses: ./.github/workflows/_build-native.yml
    with:
      target_so: 'windows'
  build-linux:
    uses: ./.github/workflows/_build-native.yml
    with:
      target_so: 'linux'
