name: Deploy

on:
  push:
    branches:
      - main
jobs:
  generate-bindings:
    uses: ./.github/workflows/_generate.yml
  build-windows:
    uses: ./.github/workflows/_build-native.yml
    with:
      target_so: 'windows'
  build-linux:
    uses: ./.github/workflows/_build-native.yml
    with:
      target_so: 'linux'
