name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-bindings:
    uses: ./.github/workflows/generate.yml
  build-windows:
    uses: ./.github/workflows/build-native.yml
    with:
      target_so: 'windows'
  build-linux:
    uses: ./.github/workflows/build-native.yml
    with:
      target_so: 'linux'
